raspimouse:
  # Publish
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  # Controllers 
  
  # left_joint_position_controller:
  #   type: "position_controllers/JointPositionController"
  #   joint: left_wheel_joint
  #
  # right_joint_position_controller:
  #   type: "position_controllers/JointPositionController"
  #   joint: right_wheel_joint

  diff_drive_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'left_wheel_joint'
    right_wheel : 'right_wheel_joint'
    publish_rate: 50 #default: 50
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.085
    wheel_radius : 0.024
    # Wheel separation and radius multipliers
    wheel_radius_multiplier: 1.0 #default: 1.0
    wheel_separation_multiplier: 1.0 #default: 1.0
    base_frame_id: base_footprint
